CREATE DATABASE marvel;
USE marvel;
-- Product Table

CREATE TABLE IF NOT EXISTS Products (
  Product_ID INT(6) NOT NULL,
  Product_Name VARCHAR(30) NOT NULL UNIQUE,
  Types VARCHAR(30) NOT NULL, 
  Specs VARCHAR(200),
  Description VARCHAR(100),
  Company VARCHAR(50),
  PRIMARY KEY (Product_ID)
);



-- Seller Table

CREATE TABLE IF NOT EXISTS Seller (
  Seller_ID INT(6) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL UNIQUE,
  Phone CHAR(10) NOT NULL,
  Address VARCHAR(200) NOT NULL,
  City VARCHAR(30) NOT NULL,
  State VARCHAR(30) NOT NULL,
  Pincode VARCHAR(10) NOT NULL,
  Star DECIMAL(2,1),
  Email VARCHAR(100) NOT NULL,
  PRIMARY KEY (Seller_ID)
);



-- Inventory Table

CREATE TABLE IF NOT EXISTS Inventory (
  Inven_ID INT(10) NOT NULL,
  Seller_ID INT(6) NOT NULL,
  Product_ID INT(6) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (Inven_ID),
  FOREIGN KEY (Seller_ID)
    REFERENCES Seller (Seller_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (Product_ID)    
    REFERENCES Products (Product_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);



-- Customer Table

CREATE TABLE IF NOT EXISTS Customer (
  Customer_ID INT(6) NOT NULL,
  Name VARCHAR(30) NOT NULL,
  Email VARCHAR(45) NOT NULL,
  Address VARCHAR(200) NOT NULL,
  City VARCHAR(30) NOT NULL,
  State VARCHAR(30) NOT NULL,
  Pincode VARCHAR(10) NOT NULL,
  Phone CHAR(10) NOT NULL,
  Orders INT NOT NULL DEFAULT 0,
  PRIMARY KEY (Customer_ID)
);


-- Cart Tale

CREATE TABLE IF NOT EXISTS Cart (
  Cart_ID INT(10) NOT NULL AUTO_INCREMENT,
  Item_qty INT NOT NULL,
  Customer INT(6) NOT NULL,
  PRIMARY KEY (Cart_ID),
  FOREIGN KEY (Customer)    
    REFERENCES Customer (Customer_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    );


-- Rig Table

CREATE TABLE IF NOT EXISTS Rig (
  Rig_ID INT(6) NOT NULL AUTO_INCREMENT,
  Design VARCHAR(20) NULL,
  PRIMARY KEY (Rig_ID)
);


-- Order table

CREATE TABLE IF NOT EXISTS Orders (
  Order_ID INT(10) NOT NULL,
  Inven_ID INT(6) NOT NULL,
  Cart_ID INT(10) NOT NULL,
  Rig_ID INT(6) NULL,
  PRIMARY KEY (Order_ID),
  FOREIGN KEy (Inven_ID)    
    REFERENCES Inventory (Inven_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (Cart_ID)    
    REFERENCES Cart (Cart_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (Rig_ID)    
    REFERENCES Rig (Rig_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- Card Table

CREATE TABLE IF NOT EXISTS Card (
  Card_no VARCHAR(20) NOT NULL,
  Customer INT(6) NOT NULL,
  Type VARCHAR(5) NOT NULL,
  PRIMARY KEY (Card_no),
  FOREIGN KEY (Customer)    
    REFERENCES Customer (Customer_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- Transacton Table

CREATE TABLE IF NOT EXISTS Transaction (
  Tran_ID INT(6) NOT NULL AUTO_INCREMENT,
  Mode CHAR(3) NOT NULL,
  Payment DECIMAL(10,2) NOT NULL,
  Card_Num VARCHAR(20) NULL,
  Cart_ID INT(10) NOT NULL,
  PRIMARY KEY (Tran_ID),
  FOREIGN KEY (Card_Num)    
    REFERENCES Card (Card_no)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (Cart_ID)    
    REFERENCES Cart (Cart_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- Shipment Table

CREATE TABLE IF NOT EXISTS Shipment (
  Shipment_ID INT(6) NOT NULL AUTO_INCREMENT,
  Customer_ID INT(6) NOT NULL,
  Balance DECIMAL(10,2) NOT NULL,
  Tran_ID INT(6) NOT NULL,
  PRIMARY KEY (Shipment_ID),
  FOREIGN KEY (Customer_ID)    
    REFERENCES Customer (Customer_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (Tran_ID)    
    REFERENCES Transaction (Tran_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- Compatibility Table

CREATE TABLE IF NOT EXISTS Compatibility (
  Product_1 INT(6) NOT NULL,
  Product_2 INT(6) NOT NULL,
  PRIMARY KEY (Product_1, Product_2),
  FOREIGN KEY (Product_1)   
    REFERENCES Products (Product_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Product_2)   
    REFERENCES Products (Product_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
